Program - Write a program to perform average of five numbers using input () function and type conversion concept.

 
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))
num4 = float(input("Enter fourth number: "))
num5 = float(input("Enter fifth number: "))

 
average = (num1 + num2 + num3 + num4 + num5) / 5

 
print("Average =", average)