Program - Write a program to create a set,tuple, list, dictionary.

# Creating a List
my_list = [10, 20, 30, 40]
print("List:", my_list)

# Creating a Tuple
my_tuple = (1, 2, 3, 4)
print("Tuple:", my_tuple)

# Creating a Set
my_set = {100, 200, 300, 400}
print("Set:", my_set)

# Creating a Dictionary
my_dict = {
    "name": "John",
    "age": 25,
    "city": "Pune"
}
print("Dictionary:", my_dict)