Program - Write a program to understand the concept of built-in function.  

# Taking input from user
text = input("Enter a string: ")

# Using len() function
length = len(text)
print("\nLength of string:", length)

# Using capitalize() function
cap_text = text.capitalize()
print("After capitalize():", cap_text)

# Using title() function
title_text = text.title()
print("After title():", title_text)