Program - Write a program to use the concept of conditional statement.


# Taking input from user

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

# Conditional statements

if num1 == num2:
    print("Both numbers are equal")
elif num1 > num2:
    print("First number is greater than second number")
else:
    print("First number is smaller than second number")

